
GET http://localhost:8000/journals

###

GET http://localhost:8000/journals/6625cab03a242e0f80862c0c


###

POST http://localhost:8000/journals
Content-Type: application/json

{
    "name": "Learning Vite",
    "author_First_Name": "Pedro",
    "author_Last_Name": "Delgadillo",
    "entry":"Okay, so I think I finally get Vite! No more messing with tons of config files. This is a game-changer for development speed . Gotta remember the commands though..."
}
###

POST http://localhost:8000/journals
Content-Type: application/json

{
    "name": "React Router",
    "author_First_Name": "Pedro",
    "author_Last_Name": "Delgadillo",
    "entry":"Started learning React Router today. My brain hurts a little, but I think I'm getting the hang of routing components. Need to practice those nested routes though!"
}
###

POST http://localhost:8000/journals
Content-Type: application/json

{
    "name": "Vercel Deployment",
    "author_First_Name": "Pedro",
    "author_Last_Name": "Delgadillo",
    "entry":"Just deployed my first project to Vercel!  So easy and feels great to have it live. Now gotta figure out how to add a custom domain..."
}
###

POST http://localhost:8000/journals
Content-Type: application/json

{
    "name": "React Training",
    "author_First_Name": "Pedro",
    "author_Last_Name": "Delgadillo",
    "entry": "Today, I dove into learning some react! It was a fascinating journey. I found how simple it is to use images and use logic to check if that journal entry has an image. I want to implemnt a file upload that would be cool!",
    "img": "/react.png"
    }

###

DELETE http://localhost:8000/journals/6625cab03a242e0f80862c0c

###

PATCH http://localhost:8000/journals/6625a28edc14fec087339375
Content-Type: application/json

{
    "name":"Bill",
    "class":"DWA"
}